### ISSUE TITLE
Merge Link & PlaidLink components into 1 component

### ISSUE THREAD

**Issue by mitchdotdeveloper** [mitchdotdeveloper/fin_dash#19]
### Tasks
- [x] Alter passed props from `<App />`
- [x] Resolve `render()`
- [x] Resolve `state` to hold necessary fields
- [x] Refactor creation/instantiation of `Plaid` in new `<Link />`
- [x] Migrate `sendToken()` and `getItems()`
- [x] Handle `success` and `exit` cases for `Plaid Link Module`
- [x] Resolve imports throughout the Client-side
- [x] Update `link.css`

### Why?
- Migrated away from npm `react-plaid-link` package because it was unnecessary to install just to handle the `Plaid Link Module`
- Created `<PlaidLink />`, My implementation of the Plaid Link Module, but I now have `<Link />` as well
- Don't need a `<Link />` to handle my `<PlaidLink />`, thus, it should be just 1 component
