### ISSUE TITLE
Fix how <App /> is rendering/mounting <Link />

### ISSUE THREAD

**Issue by mitchdotdeveloper** [mitchdotdeveloper/fin_dash#21]
### Tasks
- [x] Remove callback `prop` passed from `<App />` to `<Link />`
- [x] Fix `prop` drilling regarding when to render `<Link />`
- [x] Use strictly `state` to handle `<Link />` render

### Why?
- Invoking a callback to manually empty the DOM tree off of `root` is an egregious anti-pattern & totally wrong
- Using `state` and conditional rendering is how it should be done
